### PR TITLE
typo + fix a possible NaN in Logic.matchLikelihood

### PR DESCRIPTION
**Pull request by ericsebesta**
I'm not sure if you'll want this change, but i felt that I should point it out. If you take this pull request to Chapter2, I can replicate it in the other chapter areas - since it appears in all of them.

### CODE REVIEW

**Comment by matthewfarwell** [comment]
The book is currently in pre-production, so we don't want to change any code at the minute. Once it goes into production, we'll have a look at this sort of thing.

**Comment by esebesta** [comment]
Oh, I totally understand. It's just a proposal in the "github way" - i.e. feel free to dismiss it or ignore it for a while. Best luck on launching the book - I'm looking forward to it!

**Comment by jsuereth** [comment]
Thanks @esebesta if I hadn't said so before.  We really appreciate it.

**Comment by esebesta** [comment]
Happy to help. I anxious await the full book! :)

**Pull request merged**
